name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore ./src/DataMasker.sln

    - name: Build
      run: dotnet build ./src/DataMasker.sln -c Release --no-restore

    - name: Test
      run: dotnet test ./src/DataMasker.Tests/DataMasker.Tests.csproj -c Release --no-build --verbosity normal
