name: Release

on: [workflow_dispatch]

jobs:
  release:
    env:
      VERSION_NUMBER: 2.0.${{github.run_number}}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore ./src/DataMasker.sln

    - name: Build
      run: dotnet build ./src/DataMasker.sln -c Release --no-restore

    - name: Test
      run: dotnet test ./src/DataMasker.Tests/DataMasker.Tests.csproj -c Release --no-build --verbosity normal

    - name: Pack Library
      run: dotnet pack ./src/DataMasker/DataMasker.csproj -c Release --no-build -o ./build/ /p:Version=${{env.VERSION_NUMBER}}

    - name: Push NuGet
      run: dotnet nuget push ./build/DataMasker.${{env.VERSION_NUMBER}}.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

    - name: Collect Library Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DataMasker.${{env.VERSION_NUMBER}}
        path: ./build/DataMasker.${{env.VERSION_NUMBER}}.nupkg

    - name: Build CLI
      run: dotnet publish ./src/DataMasker.Runner -c Release -o ./runner-build/ -r win-x64 --self-contained

    - name: Zip CLI
      run: zip -r DataMasker.Runner.zip ./runner-build/

    - name: Collect CLI Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DataMasker.Runner.${{env.VERSION_NUMBER}}
        path: ./DataMasker.Runner.zip

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "DataMasker.Runner.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{env.VERSION_NUMBER}}
