name: .NET Core

on:
  workflow_dispatch:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      VERSION_NUMBER: 2.0.${{github.run_number}}-alpha
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core    
      uses: actions/setup-dotnet@v1      
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/DataMasker/DataMasker.csproj
    - name: Build Library
      run: dotnet build ./src/DataMasker/DataMasker.csproj --configuration Release --no-restore
    - name: Publish Library
      run: dotnet pack ./src/DataMasker/DataMasker.csproj --configuration Release --no-restore -o ./build/ /p:Version=${{env.VERSION_NUMBER}}
    - name: Push Nuget
       
      run: dotnet nuget push ./build/DataMasker.${{env.VERSION_NUMBER}}.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
    - name: Collect Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: DataMasker.${{env.VERSION_NUMBER}}
        path: ./build/DataMasker.${{env.VERSION_NUMBER}}.nupkg
    - name: Build CLI
      run: dotnet publish ./src/DataMasker.Runner --configuration Release
    - name: action-zip
      uses: montudor/action-zip@v1.0.0
      with:
        args: zip -qq -r DataMasker.Runner.zip ./src/DataMasker.Runner/bin/Release/netcoreapp3.1/publish/
    - name: Collect Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: DataMasker.Runner.${{env.VERSION_NUMBER}}
        path: ./DataMasker.Runner.zip
    - name: Create Release (DataMasker.Runner)
      uses: ncipollo/release-action@v1.8.4
      with:
        artifacts: "DataMasker.Runner.zip"
        bodyFile: "ReadMe.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{env.VERSION_NUMBER}}
    
